version: "3.7"
services:
  mongodb_container:
    image: mongo:6.0.2
    environment:
      MONGO_INITDB_DATABASE: dcim
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: changeme
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data:
