version: "3.8"
services:
  api:
    image: nodejs
    build:
      dockerfile: node.Dockerfile
      context: .
    ports:
      - "3000:3000"
    volumes:
      - "./node/:/usr/src/app"
    env_file:
      - dcim.env
  mongodb_container:
    image: mongo:latest
    env_file:
      - dcim.env
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
