version: "3.7"
services:
  mongodb:
    image: mongo:6.0.2
    environment:
      MONGO_INITDB_DATABASE: heorot
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: changeme
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
  heorot-api:
    build:
      context: ../api
      dockerfile: Dockerfile.dev
      args:
        # set to user, uid, & gid of user with access to config files & grendel socket
        UNAME: grendel
        UID: 999
        GID: 999
    ports:
      - 443:443 # make sure to update config.js accordingly
    volumes:
      - /var/lib/grendel/grendel-api.socket:/var/lib/grendel/grendel-api.socket
      - type: bind
        source: ../api
        target: /usr/src/app/
    links:
      - mongodb
    restart: unless-stopped
  heorot-client:
    build:
      context: ../client
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ../client
        target: /usr/src/app/
    links:
      - heorot-api
    restart: unless-stopped
volumes:
  mongodb_data:
